version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: scriptwf
      POSTGRES_PASSWORD: scriptwf
      POSTGRES_DB: scriptwf
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    command: ["node", "dist/main.js"]
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://scriptwf:scriptwf@db:5432/scriptwf?schema=public
      JWT_SECRET: devsecret
    volumes:
      - ./backend/dist:/app/dist
      - ./backend/prisma:/app/prisma
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    environment:
      # Em desenvolvimento, apontar para backend direto via host.docker.internal se necessário
      VITE_API_BASE_URL: http://localhost/api
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata_dev:
