services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://scriptwfdev:Dev2024ScriptWF3mL8@db:5432/scriptwf_dev
      JWT_SECRET: ${JWT_SECRET}
      WF_HEADLESS_DEFAULT: false
      INITIAL_GRACE_MS: 40000
      POLL_INTERVAL_MS: 3000
      MAX_PERSIST_ATTEMPTS: 15
      MAX_TOTAL_MS: 90000
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./temp:/app/temp  # Para arquivos temporários

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:3000/api
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: scriptwfdev
      POSTGRES_PASSWORD: Dev2024ScriptWF3mL8
      POSTGRES_DB: scriptwf_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata_local:/var/lib/postgresql/data

volumes:
  pgdata_local: